### ISSUE TITLE
`Res.affected_rows` not available where it's needed

### ISSUE THREAD

**Issue by paurkedal** [andrenth/ocaml-mariadb#14]
I think there is a design flaw in the way `mysql_stmt_affected_rows` is exposed.  `Stmt.execute` returns `None : Res.t option` for `INSERT` or `UPDATE` statements, making `Res.affected_rows` unavailable.  I can see the logic of placing this function there, though.  I guess the options are to move the function to `Stmt.t` or synthesising a `Res.t` with `num_rows = 0` and a `fetch` consistent with it?

**Comment by andrenth** [comment]
I think the idea was to not allow `num_rows` to be called after an `INSERT` or `UPDATE` because it doesn't make sense, and I probably added `affected_rows` later and didn't consider the `None` result.

I think I'll simply return a `Res.t` from `Stmt.execute` and get rid of the option type.

**Comment by andrenth** [comment]
Commit 59f30f does that. Please tell me what you think.

**Comment by paurkedal** [comment]
Yes, I think this was the nicest option.  Will the release be 0.10.0 (so I get my version constraints right)?

**Comment by andrenth** [comment]
Yep, 0.10.0. I'll publish soon.

**Comment by paurkedal** [comment]
Great, thanks!

**Comment by andrenth** [comment]
Pull request [submitted to opam-repository](https://github.com/ocaml/opam-repository/pull/10887).
