### ISSUE TITLE
ctypes.foreign dependency is not needed

### ISSUE THREAD

**Issue by ygrek** [andrenth/ocaml-mariadb#26]
it brings in libffi runtime dependency which is totally unnecessary

fix:
```
diff --git a/_oasis b/_oasis
index 3fd581c..9d913b9 100644
--- a/_oasis
+++ b/_oasis
@@ -54,7 +54,7 @@ Library "mariadb_bindings"
   Modules:          Ffi_bindings
   ByteOpt:          -warn-error +1..45
   NativeOpt:        -warn-error +1..45
-  BuildDepends:     ctypes.stubs, ctypes.foreign
+  BuildDepends:     ctypes.stubs
 
 Executable "ffi_stubgen"
   Install:          false
```
followed by `oasis setup`

**Comment by ygrek** [comment]
@andrenth do you have any reservations against this?

**Comment by ygrek** [comment]
ping

**Comment by andrenth** [comment]
Hi

Sorry for the delay. No reservations, I just haven't been working with OCaml lately, so my time is really limited for maintaining my libraries.

I'll apply this, rebuild my dev environment and see if I still remember how to make a release :)

**Comment by andrenth** [comment]
Just submitted version 1.1.2.

**Comment by ygrek** [comment]
Thanks!

**Comment by ygrek** [comment]
ctypes-foreign dependency is present in opam file and made it to opam-repository.
