### ISSUE TITLE
Mariadb 10.5 Insert ... Returning

### ISSUE THREAD

**Issue by JoshSmithCode** [andrenth/ocaml-mariadb#33]
Hi, I'm new to Ocaml and have been experimenting with this, but can't seem to figure out what I'm doing wrong. 

The query I'm using is "INSERT INTO users VALUES (NULL) RETURNING id" just to insert an empty user and get the insert ID. 

If I call `Res.num_rows` and pass the result it returns that there is 1 result row, but when I try to use Res.fetch to get the resulting ID I'm not able to, it always seems to return an `Ok` but with `None` instead of `Some row`.

Apologies if there's a simple solution to this or something I'm misunderstanding.

**Comment by apeschar** [comment]
It seems that `mysql_stmt_result_metadata` returns NULL for `INSERT ... RETURNING` queries, leading ocaml-mariadb to believe that the statement will not return any rows.

Either we should not rely on prepared statement metadata, or `mysql_stmt_result_metadata` should be fixed in the MariaDB client libraries.

A workaround would be to issue `SELECT LAST_INSERT_ID()` after your query, or if you need a different column, to use `RETURNING @my_col := my_col` followed by `SELECT @my_col`.

**Comment by apeschar** [comment]
Statement metadata can change after statements are prepared.

>  Metadata changes to tables or views referred to by prepared statements are detected and cause automatic repreparation of the statement when it is next executed. For more information, see [Caching of Prepared Statements and Stored Programs](https://dev.mysql.com/doc/refman/8.0/en/statement-caching.html). 

https://dev.mysql.com/doc/c-api/8.0/en/mysql-stmt-execute.html

It's not explicitly mentioned there, but when using `INSERT ... RETURNING` the initial metadata after statement preparation is unset (and mysql_stmt_field_count returns 0). After execution mysql_stmt_field_count returns the correct amount of columns, and the metadata is presumably available.

ocaml-mariadb should be changed to delay retrieval of statement metadata until after the first execution.

**Comment by apeschar** [comment]
Referenced PR should fix this problem. As for reproducing this issue, try these steps:

Create the test database:

    mysqladmin create test

Create the test table:

    mysql test <<EOF
    CREATE TABLE test (
      id int(11) NOT NULL AUTO_INCREMENT PRIMARY KEY,
      x varchar(255) DEFAULT NULL,
    )
    EOF

Run the example with the offending query:

    ocamlfind ocamlopt -linkpkg -package mariadb ./examples/blocking/blocking_example.ml
    OCAML_MARIADB_DB=test OCAML_MARIADB_QUERY="INSERT INTO test SET x = ? RETURNING id" ./a.out

We expect to see a result consisting of a single row with the ID of the inserted row. Instead, we get nothing.
