### ISSUE TITLE
Maintenance Status

### ISSUE THREAD

**Issue by paurkedal** [andrenth/ocaml-mariadb#53]
I'm wondering if this package needs a new maintainer?  We could at least use an OCaml 5 compatible release.

**Comment by goband34** [comment]
Besides compatibility changes, did you have any other changes in mind? I am not a maintainer here but I was interested in the library for a personal project

**Comment by paurkedal** [comment]
I am not thinking about any major changes, but someone to review and merge pull requests, look at issues, and cut releases.  I intend to make a post to discuss.ocaml.org if we don't hear from the author.

**Comment by paurkedal** [comment]
@ygrek I have noticed you have been handling merge requests lately, so if you are fine with the current arrangement, maybe I can close this issue? I am also available to help out if needed, at least for the time being.

**Comment by ygrek** [comment]
I don't have access to the settings of the repository, so cannot do admin things, but I have push rights and so trying to keep code up-to-date.
Would appreciate help with reviewing PRs ofcourse :)

**Comment by paurkedal** [comment]
Thanks for the clarification.  I think that makes it inconvenient to make releases, so I propose that we try to get it [moved to the ocaml-community](https://github.com/ocaml-community/meta) organization, or let me know if you have other ideas.  Shall I open an issue there, and propose we both get admin access?

**Comment by ygrek** [comment]
i don't really care what is the url of this repo, up to @andrenth :)
i can do releases alright

**Comment by paurkedal** [comment]
Yeah, the URL doesn't matter, it was more to hand over the access management.  But if you can make releases and you are okay with the current arrangement, then I'm happy with keeping things as they are too.  Thanks again for clarifying the status.

**Comment by andrenth** [comment]
Hey guys, sorry for not being responsive. I'm happy to hand over the project if it makes the maintenance easier.

**Comment by paurkedal** [comment]
@andrenth Thanks for the response.  Do you have a preference?  I have been assuming you have moved on to other projects, so offloading a bit of admin work and notifications would be a good thing, but I'll not push for anything unless you or @ygrek think it should be done.

**Comment by andrenth** [comment]
I think the easiest thing to do would be to transfer the project to someone willing to maintain it. Whatever works better for you guys I’m fine with it.

**Comment by paurkedal** [comment]
@ygrek In that case I suggest we proceed.  Shall I open a request for ocaml-community, or do you have other ideas?

**Comment by ygrek** [comment]
ocaml-community sounds good to me
